name: Joao victor Server
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy para o server
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --dedlete"
          SOURCE: "sport-player"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}
